# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dialog_0406_tra_2d_xy_contour.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(814, 740)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.verticalLayout_plot = QVBoxLayout()
        self.verticalLayout_plot.setObjectName(u"verticalLayout_plot")
        self.verticalLayout_plot.setSizeConstraint(QLayout.SetMinimumSize)

        self.gridLayout.addLayout(self.verticalLayout_plot, 0, 0, 1, 1)

        self.verticalLayout_control = QVBoxLayout()
        self.verticalLayout_control.setObjectName(u"verticalLayout_control")
        self.verticalLayout_control.setSizeConstraint(QLayout.SetMinimumSize)
        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_control.addItem(self.verticalSpacer)

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setMinimumSize(QSize(396, 160))
        self.groupBox.setMaximumSize(QSize(396, 160))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(25, 35, 181, 26))
        self.label.setMinimumSize(QSize(150, 0))
        self.label.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_graphic_critical_heat_flux = QLineEdit(self.groupBox)
        self.lineEdit_graphic_critical_heat_flux.setObjectName(u"lineEdit_graphic_critical_heat_flux")
        self.lineEdit_graphic_critical_heat_flux.setGeometry(QRect(215, 35, 91, 26))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(25, 70, 181, 26))
        self.label_2.setMinimumSize(QSize(0, 0))
        self.label_2.setMaximumSize(QSize(16777215, 16777215))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(25, 105, 181, 26))
        self.horizontalSlider_graphic_line_thickness = QSlider(self.groupBox)
        self.horizontalSlider_graphic_line_thickness.setObjectName(u"horizontalSlider_graphic_line_thickness")
        self.horizontalSlider_graphic_line_thickness.setGeometry(QRect(215, 105, 91, 26))
        self.horizontalSlider_graphic_line_thickness.setMinimum(0)
        self.horizontalSlider_graphic_line_thickness.setMaximum(10)
        self.horizontalSlider_graphic_line_thickness.setValue(5)
        self.horizontalSlider_graphic_line_thickness.setOrientation(Qt.Horizontal)
        self.horizontalSlider_graphic_line_thickness.setInvertedAppearance(False)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(315, 35, 51, 26))
        self.label_7.setMinimumSize(QSize(0, 0))
        self.label_7.setMaximumSize(QSize(16777215, 16777215))
        self.label_graphic_contour_label_font_size = QLabel(self.groupBox)
        self.label_graphic_contour_label_font_size.setObjectName(u"label_graphic_contour_label_font_size")
        self.label_graphic_contour_label_font_size.setGeometry(QRect(315, 70, 51, 26))
        self.label_graphic_contour_label_font_size.setMinimumSize(QSize(0, 0))
        self.label_graphic_contour_label_font_size.setMaximumSize(QSize(16777215, 16777215))
        self.label_graphic_line_thickness = QLabel(self.groupBox)
        self.label_graphic_line_thickness.setObjectName(u"label_graphic_line_thickness")
        self.label_graphic_line_thickness.setGeometry(QRect(315, 105, 51, 26))
        self.label_graphic_line_thickness.setMinimumSize(QSize(0, 0))
        self.label_graphic_line_thickness.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalSlider_graphic_contour_font_size = QSlider(self.groupBox)
        self.horizontalSlider_graphic_contour_font_size.setObjectName(u"horizontalSlider_graphic_contour_font_size")
        self.horizontalSlider_graphic_contour_font_size.setGeometry(QRect(215, 70, 91, 26))
        self.horizontalSlider_graphic_contour_font_size.setMinimum(0)
        self.horizontalSlider_graphic_contour_font_size.setMaximum(20)
        self.horizontalSlider_graphic_contour_font_size.setValue(12)
        self.horizontalSlider_graphic_contour_font_size.setOrientation(Qt.Horizontal)
        self.horizontalSlider_graphic_contour_font_size.setInvertedAppearance(False)

        self.verticalLayout_control.addWidget(self.groupBox)

        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setMinimumSize(QSize(396, 431))
        self.groupBox_2.setMaximumSize(QSize(396, 441))
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(25, 35, 86, 26))
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(25, 70, 86, 26))
        self.lineEdit_solver_x = QLineEdit(self.groupBox_2)
        self.lineEdit_solver_x.setObjectName(u"lineEdit_solver_x")
        self.lineEdit_solver_x.setGeometry(QRect(110, 35, 61, 26))
        self.lineEdit_solver_z = QLineEdit(self.groupBox_2)
        self.lineEdit_solver_z.setObjectName(u"lineEdit_solver_z")
        self.lineEdit_solver_z.setGeometry(QRect(310, 70, 61, 26))
        self.lineEdit_solver_y = QLineEdit(self.groupBox_2)
        self.lineEdit_solver_y.setObjectName(u"lineEdit_solver_y")
        self.lineEdit_solver_y.setGeometry(QRect(310, 35, 61, 26))
        self.lineEdit_solver_delta = QLineEdit(self.groupBox_2)
        self.lineEdit_solver_delta.setObjectName(u"lineEdit_solver_delta")
        self.lineEdit_solver_delta.setGeometry(QRect(110, 70, 61, 26))
        self.label_15 = QLabel(self.groupBox_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(225, 70, 86, 26))
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(225, 35, 86, 26))
        self.tableView_emitters = QTableView(self.groupBox_2)
        self.tableView_emitters.setObjectName(u"tableView_emitters")
        self.tableView_emitters.setGeometry(QRect(25, 135, 346, 116))
        self.tableView_emitters.setMaximumSize(QSize(396, 16777215))
        self.label_13 = QLabel(self.groupBox_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(25, 105, 86, 26))
        self.pushButton_emitter_list_append = QPushButton(self.groupBox_2)
        self.pushButton_emitter_list_append.setObjectName(u"pushButton_emitter_list_append")
        self.pushButton_emitter_list_append.setGeometry(QRect(110, 105, 26, 26))
        self.pushButton_emitter_list_remove = QPushButton(self.groupBox_2)
        self.pushButton_emitter_list_remove.setObjectName(u"pushButton_emitter_list_remove")
        self.pushButton_emitter_list_remove.setGeometry(QRect(145, 105, 26, 26))
        self.tableView_receivers = QTableView(self.groupBox_2)
        self.tableView_receivers.setObjectName(u"tableView_receivers")
        self.tableView_receivers.setGeometry(QRect(25, 290, 221, 116))
        self.tableView_receivers.setMaximumSize(QSize(396, 16777215))
        self.pushButton_receiver_list_remove = QPushButton(self.groupBox_2)
        self.pushButton_receiver_list_remove.setObjectName(u"pushButton_receiver_list_remove")
        self.pushButton_receiver_list_remove.setGeometry(QRect(145, 260, 26, 26))
        self.label_14 = QLabel(self.groupBox_2)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(25, 260, 86, 26))
        self.pushButton_receiver_list_append = QPushButton(self.groupBox_2)
        self.pushButton_receiver_list_append.setObjectName(u"pushButton_receiver_list_append")
        self.pushButton_receiver_list_append.setGeometry(QRect(110, 260, 26, 26))
        self.pushButton_example = QPushButton(self.groupBox_2)
        self.pushButton_example.setObjectName(u"pushButton_example")
        self.pushButton_example.setGeometry(QRect(275, 290, 96, 26))
        self.pushButton_example.setMinimumSize(QSize(56, 26))
        self.pushButton_example.setMaximumSize(QSize(96, 26))
        self.pushButton_refresh = QPushButton(self.groupBox_2)
        self.pushButton_refresh.setObjectName(u"pushButton_refresh")
        self.pushButton_refresh.setGeometry(QRect(275, 320, 96, 26))
        self.pushButton_refresh.setMinimumSize(QSize(56, 26))
        self.pushButton_refresh.setMaximumSize(QSize(96, 26))
        self.pushButton_save_figure = QPushButton(self.groupBox_2)
        self.pushButton_save_figure.setObjectName(u"pushButton_save_figure")
        self.pushButton_save_figure.setGeometry(QRect(275, 350, 96, 26))
        self.pushButton_save_figure.setMinimumSize(QSize(96, 26))
        self.pushButton_save_figure.setMaximumSize(QSize(96, 26))
        self.pushButton_submit = QPushButton(self.groupBox_2)
        self.pushButton_submit.setObjectName(u"pushButton_submit")
        self.pushButton_submit.setGeometry(QRect(275, 380, 96, 26))
        self.pushButton_submit.setMinimumSize(QSize(96, 26))
        self.pushButton_submit.setMaximumSize(QSize(96, 26))

        self.verticalLayout_control.addWidget(self.groupBox_2)

        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(396, 36))
        self.widget.setMaximumSize(QSize(396, 16777215))
        self.progressBar = QProgressBar(self.widget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(10, 5, 381, 26))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QSize(0, 26))
        self.progressBar.setMaximumSize(QSize(396, 26))
        self.progressBar.setValue(0)

        self.verticalLayout_control.addWidget(self.widget)


        self.gridLayout.addLayout(self.verticalLayout_control, 0, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 814, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Graphic Options", None))
#if QT_CONFIG(tooltip)
        self.label.setToolTip(QCoreApplication.translate("MainWindow", u"Critical heat flux countour line will be highlighted in red colour in the figure.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label.setStatusTip(QCoreApplication.translate("MainWindow", u"Critical heat flux countour line will be highlighted in red colour in the figure.", None))
#endif // QT_CONFIG(statustip)
        self.label.setText(QCoreApplication.translate("MainWindow", u"Critical heat flux", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_graphic_critical_heat_flux.setToolTip(QCoreApplication.translate("MainWindow", u"Critical heat flux countour line will be highlighted in red colour in the figure.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_graphic_critical_heat_flux.setStatusTip(QCoreApplication.translate("MainWindow", u"Critical heat flux countour line will be highlighted in red colour in the figure.", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_graphic_critical_heat_flux.setText(QCoreApplication.translate("MainWindow", u"12.6", None))
#if QT_CONFIG(tooltip)
        self.label_2.setToolTip(QCoreApplication.translate("MainWindow", u"Font size of the contour line text in the figure.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_2.setStatusTip(QCoreApplication.translate("MainWindow", u"Font size of the contour line text in the figure.", None))
#endif // QT_CONFIG(statustip)
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Contour Label Font Size", None))
#if QT_CONFIG(tooltip)
        self.label_5.setToolTip(QCoreApplication.translate("MainWindow", u"Line thickness of the defined emitter and receivers in the figure.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_5.setStatusTip(QCoreApplication.translate("MainWindow", u"Line thickness of the defined emitter and receivers in the figure.", None))
#endif // QT_CONFIG(statustip)
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"E. / R. Element Thickness", None))
#if QT_CONFIG(tooltip)
        self.horizontalSlider_graphic_line_thickness.setToolTip(QCoreApplication.translate("MainWindow", u"Line thickness of the defined emitter and receivers in the figure.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.horizontalSlider_graphic_line_thickness.setStatusTip(QCoreApplication.translate("MainWindow", u"Line thickness of the defined emitter and receivers in the figure.", None))
#endif // QT_CONFIG(statustip)
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"kW/m<sup>2<sup>", None))
        self.label_graphic_contour_label_font_size.setText(QCoreApplication.translate("MainWindow", u"12 pt", None))
        self.label_graphic_line_thickness.setText(QCoreApplication.translate("MainWindow", u"5", None))
#if QT_CONFIG(tooltip)
        self.horizontalSlider_graphic_contour_font_size.setToolTip(QCoreApplication.translate("MainWindow", u"Font size of the contour line text in the figure.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.horizontalSlider_graphic_contour_font_size.setStatusTip(QCoreApplication.translate("MainWindow", u"Font size of the contour line text in the figure.", None))
#endif // QT_CONFIG(statustip)
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Solver Inputs", None))
#if QT_CONFIG(tooltip)
        self.label_10.setToolTip(QCoreApplication.translate("MainWindow", u"(x_min, x_max), defines the space (on a z-plane) that the received heat flux will solved.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_10.setStatusTip(QCoreApplication.translate("MainWindow", u"(x_min, x_max), defines the space (on a z-plane) that the received heat flux will solved.", None))
#endif // QT_CONFIG(statustip)
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Domain X", None))
#if QT_CONFIG(tooltip)
        self.label_11.setToolTip(QCoreApplication.translate("MainWindow", u"This defines the grid resolution (i.e. dx and dy) that received heat flux will be solved.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_11.setStatusTip(QCoreApplication.translate("MainWindow", u"This defines the grid resolution (i.e. dx and dy) that received heat flux will be solved.", None))
#endif // QT_CONFIG(statustip)
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Resolution", None))
#if QT_CONFIG(tooltip)
        self.lineEdit_solver_x.setToolTip(QCoreApplication.translate("MainWindow", u"(x_min, x_max), defines the space (on a z-plane) that the received heat flux will solved.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_solver_x.setStatusTip(QCoreApplication.translate("MainWindow", u"(x_min, x_max), defines the space (on a z-plane) that the received heat flux will solved.", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_solver_x.setText("")
#if QT_CONFIG(tooltip)
        self.lineEdit_solver_z.setToolTip(QCoreApplication.translate("MainWindow", u"This defines the location of the z-plane which heat flux will be solved. Leave this empty to let the tool to work out the worst situation/height.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_solver_z.setStatusTip(QCoreApplication.translate("MainWindow", u"This defines the location of the z-plane which heat flux will be solved. Leave this empty to let the tool to work out the worst situation/height.", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_solver_z.setText("")
#if QT_CONFIG(tooltip)
        self.lineEdit_solver_y.setToolTip(QCoreApplication.translate("MainWindow", u"(y_min, y_max), defines the space (on a z-plane) that the received heat flux will solved.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_solver_y.setStatusTip(QCoreApplication.translate("MainWindow", u"(y_min, y_max), defines the space (on a z-plane) that the received heat flux will solved.", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_solver_y.setText("")
#if QT_CONFIG(tooltip)
        self.lineEdit_solver_delta.setToolTip(QCoreApplication.translate("MainWindow", u"This defines the grid resolution (i.e. dx and dy) that received heat flux will be solved.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.lineEdit_solver_delta.setStatusTip(QCoreApplication.translate("MainWindow", u"This defines the grid resolution (i.e. dx and dy) that received heat flux will be solved.", None))
#endif // QT_CONFIG(statustip)
        self.lineEdit_solver_delta.setText(QCoreApplication.translate("MainWindow", u"0.2", None))
#if QT_CONFIG(tooltip)
        self.label_15.setToolTip(QCoreApplication.translate("MainWindow", u"This defines the location of the z-plane which heat flux will be solved. Leave this empty to let the tool to work out the worst situation/height.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_15.setStatusTip(QCoreApplication.translate("MainWindow", u"This defines the location of the z-plane which heat flux will be solved. Leave this empty to let the tool to work out the worst situation/height.", None))
#endif // QT_CONFIG(statustip)
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Domain Z", None))
#if QT_CONFIG(tooltip)
        self.label_12.setToolTip(QCoreApplication.translate("MainWindow", u"(y_min, y_max), defines the space (on a z-plane) that the received heat flux will solved.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.label_12.setStatusTip(QCoreApplication.translate("MainWindow", u"(y_min, y_max), defines the space (on a z-plane) that the received heat flux will solved.", None))
#endif // QT_CONFIG(statustip)
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Domain Y", None))
#if QT_CONFIG(tooltip)
        self.tableView_emitters.setToolTip(QCoreApplication.translate("MainWindow", u"This table shows all defined emitters. Point 1 (x1, y1) and 2 (x2, y2) define the start and end of the emiter on a z-plane, accordingly.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tableView_emitters.setStatusTip(QCoreApplication.translate("MainWindow", u"This table shows all defined emitters. Point 1 (x1, y1) and 2 (x2, y2) define the start and end of the emiter on a z-plane, accordingly.", None))
#endif // QT_CONFIG(statustip)
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Emitters", None))
#if QT_CONFIG(tooltip)
        self.pushButton_emitter_list_append.setToolTip(QCoreApplication.translate("MainWindow", u"Click to insert an emitter in the table below.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_emitter_list_append.setStatusTip(QCoreApplication.translate("MainWindow", u"Click to insert an emitter in the table below.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_emitter_list_append.setText(QCoreApplication.translate("MainWindow", u"+", None))
#if QT_CONFIG(tooltip)
        self.pushButton_emitter_list_remove.setToolTip(QCoreApplication.translate("MainWindow", u"Click to remove an emitter in the table below.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_emitter_list_remove.setStatusTip(QCoreApplication.translate("MainWindow", u"Click to remove an emitter in the table below.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_emitter_list_remove.setText(QCoreApplication.translate("MainWindow", u"-", None))
#if QT_CONFIG(tooltip)
        self.tableView_receivers.setToolTip(QCoreApplication.translate("MainWindow", u"This table shows all defined receivers.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tableView_receivers.setStatusTip(QCoreApplication.translate("MainWindow", u"This table shows all defined receivers.", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(tooltip)
        self.pushButton_receiver_list_remove.setToolTip(QCoreApplication.translate("MainWindow", u"Click to remove an receiver in the table below.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_receiver_list_remove.setStatusTip(QCoreApplication.translate("MainWindow", u"Click to remove an receiver in the table below.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_receiver_list_remove.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Receivers", None))
#if QT_CONFIG(tooltip)
        self.pushButton_receiver_list_append.setToolTip(QCoreApplication.translate("MainWindow", u"Click to insert an receiver in the table below.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_receiver_list_append.setStatusTip(QCoreApplication.translate("MainWindow", u"Click to insert an receiver in the table below.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_receiver_list_append.setText(QCoreApplication.translate("MainWindow", u"+", None))
#if QT_CONFIG(tooltip)
        self.pushButton_example.setToolTip(QCoreApplication.translate("MainWindow", u"Click to generate example input parameters.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_example.setStatusTip(QCoreApplication.translate("MainWindow", u"Click to generate example input parameters.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_example.setText(QCoreApplication.translate("MainWindow", u"Example", None))
#if QT_CONFIG(tooltip)
        self.pushButton_refresh.setToolTip(QCoreApplication.translate("MainWindow", u"Click to refresh the figure. (This resets the figure layout)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_refresh.setStatusTip(QCoreApplication.translate("MainWindow", u"Click to refresh the figure. (This resets the figure layout)", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_refresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
#if QT_CONFIG(tooltip)
        self.pushButton_save_figure.setToolTip(QCoreApplication.translate("MainWindow", u"Click to save figure in image format.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_save_figure.setStatusTip(QCoreApplication.translate("MainWindow", u"Click to save figure in image format.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_save_figure.setText(QCoreApplication.translate("MainWindow", u"Save Figure", None))
#if QT_CONFIG(tooltip)
        self.pushButton_submit.setToolTip(QCoreApplication.translate("MainWindow", u"Click (or press Enter) to calculate.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.pushButton_submit.setStatusTip(QCoreApplication.translate("MainWindow", u"Click (or press Enter) to calculate.", None))
#endif // QT_CONFIG(statustip)
        self.pushButton_submit.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
#if QT_CONFIG(tooltip)
        self.progressBar.setToolTip(QCoreApplication.translate("MainWindow", u"Calculation progress.", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.progressBar.setStatusTip(QCoreApplication.translate("MainWindow", u"Calculation progress.", None))
#endif // QT_CONFIG(statustip)
    # retranslateUi

