# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'i0406_tra_2d_xy_contour.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1274, 877)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(1274, 836))
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(35, 35, 35, 35)
        self.verticalLayout_control = QVBoxLayout()
        self.verticalLayout_control.setSpacing(0)
        self.verticalLayout_control.setObjectName(u"verticalLayout_control")
        self.verticalLayout_control.setSizeConstraint(QLayout.SetMaximumSize)
        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_control.addItem(self.verticalSpacer)

        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setMinimumSize(QSize(386, 721))
        self.groupBox.setMaximumSize(QSize(386, 721))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(25, 50, 181, 26))
        self.label.setMinimumSize(QSize(150, 0))
        self.label.setMaximumSize(QSize(16777215, 16777215))
        self.lineEdit_graphic_critical_heat_flux = QLineEdit(self.groupBox)
        self.lineEdit_graphic_critical_heat_flux.setObjectName(u"lineEdit_graphic_critical_heat_flux")
        self.lineEdit_graphic_critical_heat_flux.setGeometry(QRect(215, 50, 91, 26))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(25, 85, 181, 26))
        self.label_2.setMinimumSize(QSize(0, 0))
        self.label_2.setMaximumSize(QSize(16777215, 16777215))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(25, 120, 181, 26))
        self.horizontalSlider_graphic_line_thickness = QSlider(self.groupBox)
        self.horizontalSlider_graphic_line_thickness.setObjectName(u"horizontalSlider_graphic_line_thickness")
        self.horizontalSlider_graphic_line_thickness.setGeometry(QRect(215, 120, 91, 26))
        self.horizontalSlider_graphic_line_thickness.setMinimum(0)
        self.horizontalSlider_graphic_line_thickness.setMaximum(10)
        self.horizontalSlider_graphic_line_thickness.setValue(2)
        self.horizontalSlider_graphic_line_thickness.setOrientation(Qt.Horizontal)
        self.horizontalSlider_graphic_line_thickness.setInvertedAppearance(False)
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(315, 50, 51, 26))
        self.label_7.setMinimumSize(QSize(0, 0))
        self.label_7.setMaximumSize(QSize(16777215, 16777215))
        self.label_graphic_contour_label_font_size = QLabel(self.groupBox)
        self.label_graphic_contour_label_font_size.setObjectName(u"label_graphic_contour_label_font_size")
        self.label_graphic_contour_label_font_size.setGeometry(QRect(315, 85, 51, 26))
        self.label_graphic_contour_label_font_size.setMinimumSize(QSize(0, 0))
        self.label_graphic_contour_label_font_size.setMaximumSize(QSize(16777215, 16777215))
        self.label_graphic_line_thickness = QLabel(self.groupBox)
        self.label_graphic_line_thickness.setObjectName(u"label_graphic_line_thickness")
        self.label_graphic_line_thickness.setGeometry(QRect(315, 120, 51, 26))
        self.label_graphic_line_thickness.setMinimumSize(QSize(0, 0))
        self.label_graphic_line_thickness.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalSlider_graphic_contour_font_size = QSlider(self.groupBox)
        self.horizontalSlider_graphic_contour_font_size.setObjectName(u"horizontalSlider_graphic_contour_font_size")
        self.horizontalSlider_graphic_contour_font_size.setGeometry(QRect(215, 85, 91, 26))
        self.horizontalSlider_graphic_contour_font_size.setMinimum(0)
        self.horizontalSlider_graphic_contour_font_size.setMaximum(20)
        self.horizontalSlider_graphic_contour_font_size.setValue(9)
        self.horizontalSlider_graphic_contour_font_size.setOrientation(Qt.Horizontal)
        self.horizontalSlider_graphic_contour_font_size.setInvertedAppearance(False)
        self.label_graphic_z = QLabel(self.groupBox)
        self.label_graphic_z.setObjectName(u"label_graphic_z")
        self.label_graphic_z.setGeometry(QRect(25, 155, 181, 26))
        self.doubleSpinBox_graphic_z = QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_graphic_z.setObjectName(u"doubleSpinBox_graphic_z")
        self.doubleSpinBox_graphic_z.setGeometry(QRect(215, 155, 91, 26))
        self.doubleSpinBox_graphic_z.setDecimals(3)
        self.doubleSpinBox_graphic_z.setMaximum(5.000000000000000)
        self.doubleSpinBox_graphic_z.setValue(1.000000000000000)
        self.checkBox_max_heat_flux = QCheckBox(self.groupBox)
        self.checkBox_max_heat_flux.setObjectName(u"checkBox_max_heat_flux")
        self.checkBox_max_heat_flux.setGeometry(QRect(315, 155, 51, 26))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 20, 341, 26))
        self.pushButton_refresh = QPushButton(self.groupBox)
        self.pushButton_refresh.setObjectName(u"pushButton_refresh")
        self.pushButton_refresh.setGeometry(QRect(25, 195, 96, 26))
        self.pushButton_refresh.setMinimumSize(QSize(56, 26))
        self.pushButton_refresh.setMaximumSize(QSize(96, 26))
        self.pushButton_save_figure = QPushButton(self.groupBox)
        self.pushButton_save_figure.setObjectName(u"pushButton_save_figure")
        self.pushButton_save_figure.setGeometry(QRect(270, 195, 96, 26))
        self.pushButton_save_figure.setMinimumSize(QSize(96, 26))
        self.pushButton_save_figure.setMaximumSize(QSize(96, 26))
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 270, 86, 26))
        self.tableView_receivers = QTableView(self.groupBox)
        self.tableView_receivers.setObjectName(u"tableView_receivers")
        self.tableView_receivers.setGeometry(QRect(30, 545, 336, 116))
        self.tableView_receivers.setMaximumSize(QSize(396, 16777215))
        self.tableView_receivers.setSortingEnabled(True)
        self.lineEdit_solver_z = QLineEdit(self.groupBox)
        self.lineEdit_solver_z.setObjectName(u"lineEdit_solver_z")
        self.lineEdit_solver_z.setGeometry(QRect(305, 305, 61, 26))
        self.lineEdit_solver_z.setStyleSheet(u"")
        self.tableView_emitters = QTableView(self.groupBox)
        self.tableView_emitters.setObjectName(u"tableView_emitters")
        self.tableView_emitters.setGeometry(QRect(30, 380, 336, 116))
        self.tableView_emitters.setMaximumSize(QSize(396, 16777215))
        self.tableView_emitters.setSortingEnabled(True)
        self.tableView_emitters.verticalHeader().setVisible(False)
        self.label_12 = QLabel(self.groupBox)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(215, 270, 86, 26))
        self.lineEdit_solver_y = QLineEdit(self.groupBox)
        self.lineEdit_solver_y.setObjectName(u"lineEdit_solver_y")
        self.lineEdit_solver_y.setGeometry(QRect(305, 270, 61, 26))
        self.pushButton_emitter_list_remove = QPushButton(self.groupBox)
        self.pushButton_emitter_list_remove.setObjectName(u"pushButton_emitter_list_remove")
        self.pushButton_emitter_list_remove.setGeometry(QRect(340, 345, 26, 26))
        self.label_15 = QLabel(self.groupBox)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(215, 305, 86, 26))
        self.pushButton_receiver_list_remove = QPushButton(self.groupBox)
        self.pushButton_receiver_list_remove.setObjectName(u"pushButton_receiver_list_remove")
        self.pushButton_receiver_list_remove.setGeometry(QRect(340, 510, 26, 26))
        self.label_11 = QLabel(self.groupBox)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 305, 86, 26))
        self.lineEdit_solver_x = QLineEdit(self.groupBox)
        self.lineEdit_solver_x.setObjectName(u"lineEdit_solver_x")
        self.lineEdit_solver_x.setGeometry(QRect(120, 270, 61, 26))
        self.label_13 = QLabel(self.groupBox)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(30, 345, 86, 26))
        self.pushButton_receiver_list_append = QPushButton(self.groupBox)
        self.pushButton_receiver_list_append.setObjectName(u"pushButton_receiver_list_append")
        self.pushButton_receiver_list_append.setGeometry(QRect(305, 510, 26, 26))
        self.pushButton_emitter_list_append = QPushButton(self.groupBox)
        self.pushButton_emitter_list_append.setObjectName(u"pushButton_emitter_list_append")
        self.pushButton_emitter_list_append.setGeometry(QRect(305, 345, 26, 26))
        self.label_14 = QLabel(self.groupBox)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(30, 510, 86, 26))
        self.lineEdit_solver_delta = QLineEdit(self.groupBox)
        self.lineEdit_solver_delta.setObjectName(u"lineEdit_solver_delta")
        self.lineEdit_solver_delta.setGeometry(QRect(120, 305, 61, 26))
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 235, 346, 26))
        self.progressBar = QProgressBar(self.groupBox)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(20, 675, 346, 26))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QSize(0, 26))
        self.progressBar.setMaximumSize(QSize(396, 26))
        self.progressBar.setValue(0)
        self.progressBar.setAlignment(Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)

        self.verticalLayout_control.addWidget(self.groupBox)

        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setMinimumSize(QSize(396, 36))
        self.widget.setMaximumSize(QSize(396, 36))
        self.pushButton_ok = QPushButton(self.widget)
        self.pushButton_ok.setObjectName(u"pushButton_ok")
        self.pushButton_ok.setGeometry(QRect(290, 5, 96, 26))
        self.pushButton_ok.setMinimumSize(QSize(96, 26))
        self.pushButton_ok.setMaximumSize(QSize(96, 26))
        self.pushButton_about = QPushButton(self.widget)
        self.pushButton_about.setObjectName(u"pushButton_about")
        self.pushButton_about.setGeometry(QRect(0, 5, 96, 26))
        self.pushButton_about.setMinimumSize(QSize(56, 26))
        self.pushButton_about.setMaximumSize(QSize(96, 26))
        self.pushButton_example = QPushButton(self.widget)
        self.pushButton_example.setObjectName(u"pushButton_example")
        self.pushButton_example.setGeometry(QRect(110, 5, 96, 26))
        self.pushButton_example.setMinimumSize(QSize(56, 26))
        self.pushButton_example.setMaximumSize(QSize(96, 26))

        self.verticalLayout_control.addWidget(self.widget)


        self.gridLayout.addLayout(self.verticalLayout_control, 0, 1, 1, 1)

        self.verticalLayout_plot = QVBoxLayout()
        self.verticalLayout_plot.setObjectName(u"verticalLayout_plot")
        self.verticalLayout_plot.setSizeConstraint(QLayout.SetMinimumSize)

        self.gridLayout.addLayout(self.verticalLayout_plot, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1274, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.lineEdit_graphic_critical_heat_flux, self.horizontalSlider_graphic_contour_font_size)
        QWidget.setTabOrder(self.horizontalSlider_graphic_contour_font_size, self.horizontalSlider_graphic_line_thickness)
        QWidget.setTabOrder(self.horizontalSlider_graphic_line_thickness, self.doubleSpinBox_graphic_z)
        QWidget.setTabOrder(self.doubleSpinBox_graphic_z, self.checkBox_max_heat_flux)
        QWidget.setTabOrder(self.checkBox_max_heat_flux, self.pushButton_refresh)
        QWidget.setTabOrder(self.pushButton_refresh, self.pushButton_save_figure)
        QWidget.setTabOrder(self.pushButton_save_figure, self.lineEdit_solver_x)
        QWidget.setTabOrder(self.lineEdit_solver_x, self.lineEdit_solver_y)
        QWidget.setTabOrder(self.lineEdit_solver_y, self.lineEdit_solver_delta)
        QWidget.setTabOrder(self.lineEdit_solver_delta, self.lineEdit_solver_z)
        QWidget.setTabOrder(self.lineEdit_solver_z, self.pushButton_emitter_list_append)
        QWidget.setTabOrder(self.pushButton_emitter_list_append, self.pushButton_emitter_list_remove)
        QWidget.setTabOrder(self.pushButton_emitter_list_remove, self.tableView_emitters)
        QWidget.setTabOrder(self.tableView_emitters, self.pushButton_receiver_list_append)
        QWidget.setTabOrder(self.pushButton_receiver_list_append, self.pushButton_receiver_list_remove)
        QWidget.setTabOrder(self.pushButton_receiver_list_remove, self.tableView_receivers)
        QWidget.setTabOrder(self.tableView_receivers, self.pushButton_ok)
        QWidget.setTabOrder(self.pushButton_ok, self.pushButton_about)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Critical heat flux", None))
        self.lineEdit_graphic_critical_heat_flux.setText(QCoreApplication.translate("MainWindow", u"12.6", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Contour text font size", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Emitter / receiver line thickness", None))
#if QT_CONFIG(tooltip)
        self.horizontalSlider_graphic_line_thickness.setToolTip(QCoreApplication.translate("MainWindow", u"Line thickness of the defined emitter and receivers in the figure.", None))
#endif // QT_CONFIG(tooltip)
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"kW/m<sup>2<sup>", None))
        self.label_graphic_contour_label_font_size.setText(QCoreApplication.translate("MainWindow", u"9 pt", None))
        self.label_graphic_line_thickness.setText(QCoreApplication.translate("MainWindow", u"2 pt", None))
#if QT_CONFIG(tooltip)
        self.horizontalSlider_graphic_contour_font_size.setToolTip(QCoreApplication.translate("MainWindow", u"Font size of the contour line text in the figure.", None))
#endif // QT_CONFIG(tooltip)
        self.label_graphic_z.setText(QCoreApplication.translate("MainWindow", u"Z-plane to show heat flux results", None))
        self.checkBox_max_heat_flux.setText(QCoreApplication.translate("MainWindow", u"Max.", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"<b>Preferences</b>", None))
        self.pushButton_refresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.pushButton_save_figure.setText(QCoreApplication.translate("MainWindow", u"Save Figure", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Domain X", None))
        self.lineEdit_solver_z.setText("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Domain Y", None))
        self.lineEdit_solver_y.setText("")
        self.pushButton_emitter_list_remove.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Domain Z", None))
        self.pushButton_receiver_list_remove.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Resolution", None))
        self.lineEdit_solver_x.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Emitters", None))
        self.pushButton_receiver_list_append.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButton_emitter_list_append.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Receivers", None))
        self.lineEdit_solver_delta.setText(QCoreApplication.translate("MainWindow", u"0.5", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<b>Solver input parameters</b>", None))
        self.pushButton_ok.setText(QCoreApplication.translate("MainWindow", u"Calculate", None))
        self.pushButton_about.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.pushButton_example.setText(QCoreApplication.translate("MainWindow", u"Example", None))
    # retranslateUi

